stages:
  - test

e2e_tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.39.0-focal # Official Playwright image, replace version as needed
  before_script:
    - npm install # Install project dependencies

  script:
    - npm run test # Run tests and generate JSON report
    - npm run report # Generate HTML report

  artifacts:
    paths:
      - cucumber_report.html # Save the report as an artifact for easy viewing

  only:
    - schedules
